language: go

sudo: required

go:
- 1.9

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y php5-fpm

install:
  - ls -laR /etc/php*
  - wget -O glide.tar.gz "https://github.com/Masterminds/glide/releases/download/v0.13.0/glide-v0.13.0-linux-amd64.tar.gz"
  - mkdir -p $HOME/bin
  - tar -vxz -C $HOME/bin --strip=1 -f glide.tar.gz
  - export PATH="$HOME/bin:$PATH"
  - glide i
  - go build
  - cp fpmTest/test.php /tmp/
  - sudo /etc/init.d/php5-fpm stop
  - sudo ./docker-fpm-wrapper --fpm /usr/sbin/php5-fpm --fpm-config /etc/php5/fpm/php-fpm.conf 2> /tmp/stderr &

script:
  - go test $(glide novendor)
  - go build -o fpmTest/fpmTest fpmTest/main.go
  - sudo ./fpmTest/fpmTest
  - cat /tmp/stderr

deploy:
  provider: releases
  api_key:
    secure: ahyGkxfVZOu6B6Xlqy3lVpGiqSg1UpZz6y3oTStL3neZZHaoZtZFBZzaPW+ksSQDjfMiKIFEw3oo7db4DxruCBsDaZAntcFajSMjnEVAWfauNvZKzOTEk5CMDhz9KRl6HMqhDj1EojiiHxhgGHZykqEI8zrK9ZXj816haL4NnO4ETskP0MlebvLoTV1JpsugCr8UzZwsBAchFRck0wCJnkSQTI1Nu7mE8uE12zd8xf4Tvcr072GYqYAvwKtduX+j3N/wK1iec/FSZBYEVb3Vc+43pe8sInXG9Jy3XkBTcvTvQ6NvOpkNYEfJc7mcRprp29fT13y0zddIzs/M+Zc9e2Zw2xIgt7Aehpeea5y2uy8J/SkMdtR4HP4rfRjMkWI41NfQqaXaI2XeRPjW5gcewvHcBDq90gxIMpzWasN8BjAK46HwSnjJt6wITemu5y2BpyM03MvvWvVCpeAHArqBbLSu7jotBhGsG4cCKikUFhNyL9hn2CTAVS4rAFk0z4XYwtVslkla+2n3enrOifiQ5z3YuhMb8XjyroCfwdz7A3xCdu/FEVInTT8NWWEsO4I0UQvcqIJzSnaSaX/ApHUv0P5u1/h1yKrygu/IT1VDBvu0Qjiz/PyZZUNhZTh6AbjJu5mdS6NJg/hvKSbkHYheCXPu+9r7mZAto1oDVWmyTJo=
  file: docker-fpm-wrapper
  skip_cleanup: true
  on:
    repo: code-tool/docker-fpm-wrapper
    tags: true
