deploy:
  provider: releases
  api_key:
    secure: ahyGkxfVZOu6B6Xlqy3lVpGiqSg1UpZz6y3oTStL3neZZHaoZtZFBZzaPW+ksSQDjfMiKIFEw3oo7db4DxruCBsDaZAntcFajSMjnEVAWfauNvZKzOTEk5CMDhz9KRl6HMqhDj1EojiiHxhgGHZykqEI8zrK9ZXj816haL4NnO4ETskP0MlebvLoTV1JpsugCr8UzZwsBAchFRck0wCJnkSQTI1Nu7mE8uE12zd8xf4Tvcr072GYqYAvwKtduX+j3N/wK1iec/FSZBYEVb3Vc+43pe8sInXG9Jy3XkBTcvTvQ6NvOpkNYEfJc7mcRprp29fT13y0zddIzs/M+Zc9e2Zw2xIgt7Aehpeea5y2uy8J/SkMdtR4HP4rfRjMkWI41NfQqaXaI2XeRPjW5gcewvHcBDq90gxIMpzWasN8BjAK46HwSnjJt6wITemu5y2BpyM03MvvWvVCpeAHArqBbLSu7jotBhGsG4cCKikUFhNyL9hn2CTAVS4rAFk0z4XYwtVslkla+2n3enrOifiQ5z3YuhMb8XjyroCfwdz7A3xCdu/FEVInTT8NWWEsO4I0UQvcqIJzSnaSaX/ApHUv0P5u1/h1yKrygu/IT1VDBvu0Qjiz/PyZZUNhZTh6AbjJu5mdS6NJg/hvKSbkHYheCXPu+9r7mZAto1oDVWmyTJo=
  file: docker-fpm-wrapper
  on:
    repo: code-tool/docker-fpm-wrapper

